### ISSUE TITLE
How to evaluate two custom models which are not exist in the model zoo?

### ISSUE THREAD

**Issue by fadishaar84** [allenleetc/model-comparison#1]
Hello, in the example you described for the usage of model-comparison plugin, you used two models from Model Zoo:
model_frcnn = foz.load_zoo_model('faster-rcnn-resnet50-fpn-coco-torch')
model_yolo = foz.load_zoo_model('yolov5s-coco-torch')

what if I have my custom models which do not exist inside the Model Zoo, in this case, how can I use the apply_model method to apply detections on my custom dataset :

from ultralytics import YOLO
custom_detection_model = YOLO("yolov8n.pt")
dataset.apply_model(custom_detection_model, label_field="yolo") #This does not work for me
In this case, we have to upload our custom model to Model zoo on local (using google drive), but it is not applicable. I wish if we can load our custom models without the need to use Model Zoo. I appreciate it if you could help on this matter. Thank you.

**Comment by allenleetc** [comment]
Hey @fadishaar84, 

Nice to hear from you! You're right, you don't have to add a custom model to your model zoo to add inferences (although this is certainly possible).

For YOLO models, the Voxel51 [Ultralytics integration](https://docs.voxel51.com/integrations/ultralytics.html#inference) docs show an example of running inference with a YOLO model to add inferences to a FiftyOne dataset.

[Here's another example](https://docs.voxel51.com/recipes/adding_detections.html#Adding-Object-Detections-to-a-Dataset) involving running a Torch model. Prediction labels are just labels like any other in FiftyOne.

Once you've added your model predictions, you can run the single-model evaluations and then use the Model Comparison plugin. Let me know if you are able to get going!
